language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
before_install:
  - npm install -g @angular/cli@7.3.8
install:
  - npm ci
  - npm run build
script:
  - npm test
  
 
